[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SERVER_URL = "https://rpg-chat-mfru.onrender.com"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecciones específicas para assets
[[redirects]]
  from = "/banner.svg"
  to = "/banner.svg"
  status = 200

[[redirects]]
  from = "/cartel.svg"
  to = "/cartel.svg"
  status = 200

[[redirects]]
  from = "/sprite_split/*"
  to = "/sprite_split/:splat"
  status = 200

[[redirects]]
  from = "/Items Pack/*"
  to = "/Items Pack/:splat"
  status = 200

# Headers para CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
