services:
  - type: web
    name: rpg-chat-server
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: node server/websocket-server.js
    healthCheckPath: /health
    healthCheckTimeout: 60
    healthCheckInterval: 10
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromDatabase:
          name: supabase-config
          property: url
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromDatabase:
          name: supabase-config
          property: service_role_key
